import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";   // 👈 IMPORTANT LINE!
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Interview Scheduler Voice Agent",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <Provider>     {/* 👈 Wrap children */}
          {children}
          <Toaster/>
        </Provider>
      </body>
    </html>
  );
}
